#!/bin/bash
# requires jslint.js (spidermonkey version from http://whereisandy.com/code/jslint/)
# to be in path

if [ -z $1 ];then
	echo "needs js file as argument"
	exit 1
fi
if [ ! -f $1 ];then
	echo "could not find javascript file: $1"
	exit 1
fi
#echo "running jslint on $1"
cat $1 | jslint.js
