#!/bin/bash
# requires jslint.js (spidermonkey version from http://whereisandy.com/code/jslint/)
# to be in path

if [ -z $1 ];then
	echo "needs js file as argument"
	exit 1
fi
if [ ! -f $1 ];then
	echo "could not find javascript file: $1"
	exit 1
fi
OPTIONS="$JSLINT_HOME/options/default_options.js"

#second parameter is (optional) jslint options (filepath of file with options in comment)
#otherwise default options file is used (in same dir)
if [ ! -z $2 ];then

if [ ! -f $2 ];then
	echo "could not find options file: $2"
	exit 1
fi
OPTIONS=$2
fi
#we need to decrement the line numbers by the number of lines in the options file
echo '
' > newline
cat $OPTIONS $1 newline | jslint.js | $JSLINT_HOME/fixLineNumbers.pl $(wc -l $OPTIONS)
rm newline
